apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service.yaml

configurations:
  - kustomizeconfig.yaml

labels:
  - pairs:
      app.kubernetes.io/name: todo
    includeSelectors: true

