nameReference:
  - kind: Service
    version: v1
    fieldSpecs:
      - kind: Rollout
        group: argoproj.io
        version: v1alpha1
        path: spec/strategy/canary/stableService
      - kind: Rollout
        group: argoproj.io
        version: v1alpha1
        path: spec/strategy/canary/canaryService

