apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base-rollout

namespace: production

nameSuffix: -prod

patches:
  - path: patches/rollout.yaml

images:
  - name: ghcr.io/wookiesrpeople2/todo-api-node:latest
    newTag: main


